Added support for PHP >7.2
phillipsdata/minphp-record pull request #9
Opened 2022-04-19 19:37 UTC by abdyfranco

2022-04-19 20:59 UTC, tysonphillips commented on composer.json
> +        "php": ">=7.2.0",
but the null coalescing operator is introduced in 7.0?

2022-04-20 17:09 UTC, JReissmueller requested changes

2022-04-20 17:09 UTC, JReissmueller commented on src/Record.php
> +        $sql .= strlen($this->join_sql ?? '') > 0
I don't think it's necessary to make this backward incompatible.  We could change this to
```
$sql .= (isset($this->join_sql) && (strlen($this->join_sql) > 0))
```

2022-04-21 17:15 UTC, JReissmueller approved these changes

2022-04-21 17:15 UTC, merged